# Neutral fallback used for pure evaluation before configure-host.sh runs.
# Local activation uses the ignored hosts/local.nix generated by that script.
{
  configuration = "macbook";
  username = "configure-host-first";
  homeDirectory = "/Users/configure-host-first";
  system = "aarch64-darwin";
}
