#!/usr/bin/env bash
# Generate the ignored host profile for the macOS account running this script.
set -euo pipefail

cd "$(dirname "$0")/.."

if [ "$(uname -s)" != "Darwin" ]; then
  echo "error: this setup supports macOS only" >&2
  exit 1
fi

username=$(id -un)
home_directory=${HOME:?HOME is not set}

case "$username" in
  (*[!A-Za-z0-9._-]*|'')
    echo "error: unsupported account name: $username" >&2
    exit 1
    ;;
esac

case "$home_directory" in
  (*[\"\\'|'\&]*|'')
    echo "error: unsupported home-directory path: $home_directory" >&2
    exit 1
    ;;
esac

if [ ! -d "$home_directory" ]; then
  echo "error: home directory does not exist: $home_directory" >&2
  exit 1
fi

case "$(uname -m)" in
  arm64) system=aarch64-darwin ;;
  x86_64) system=x86_64-darwin ;;
  *)
    echo "error: unsupported Mac architecture: $(uname -m)" >&2
    exit 1
    ;;
esac

host_file=hosts/local.nix
{
  printf '%s\n' '# Generated by scripts/configure-host.sh; do not commit.'
  printf '%s\n' '{'
  printf '  configuration = "macbook";\n'
  printf '  username = "%s";\n' "$username"
  printf '  homeDirectory = "%s";\n' "$home_directory"
  printf '  system = "%s";\n' "$system"
  printf '%s\n' '}'
} > "$host_file"

echo "Configured $host_file:"
echo "  account:      $username"
echo "  home:         $home_directory"
echo "  architecture: $system"

for program in /nix/var/nix/profiles/default/bin/nix /opt/homebrew/bin/brew; do
  if [ -x "$program" ]; then
    echo "  found:        $program"
  else
    echo "  missing:      $program" >&2
    missing=1
  fi
done

if [ "${missing:-0}" -ne 0 ]; then
  echo "Install the missing prerequisite above, then rerun this script." >&2
  exit 1
fi
